export type DoctorLocale = "en" | "tr";

export const doctorTabTitle: Record<DoctorLocale, string> = {
  en: "Hiros | Doctor Panel",
  tr: "Hiros | Hekim Paneli",
};

const en = {
  nav: {
    now: "Recent activity",
    cases: "Cases",
    patients: "Patients",
    agenda: "Agenda",
    messages: "Messages",
    settings: "Settings",
  },
  header: {
    languageEn: "EN",
    languageTr: "TR",
    account: "Account",
    settings: "Settings",
    logout: "Log out",
    signedInAs: "Signed in as",
  },
  pages: {
    now: "Recent activity",
    cases: "Cases overview",
    patients: "Patients in treatment",
    agenda: "Agenda",
    messages: "Messages",
    settings: "Settings",
    patientProfile: "Patient profile",
    patientNotFound: "Patient not found",
  },
  now: {
    loading: "Loading the queue…",
    empty: "Nothing waiting. New cases, visit requests, today’s calls, and unread messages will land here.",
    newCase: "New case",
    visitRequest: "Visit request",
    callToday: "Call today",
    unreadMessage: "Unread message",
  },
  cases: {
    search: "Search by Case ID",
    pending: "Pending Review",
    approved: "Approved",
    declined: "Declined",
    all: "All cases",
    flagged: "Flagged only",
    red: "Red only",
    orange: "Orange only",
    green: "Green only",
    infoRequested: "Info requested",
    refresh: "Refresh",
    empty: "No cases in this view.",
    emptyNone: "No submitted intakes yet. Completed patient intakes will appear here.",
    emptyTab: "No cases to show in this tab.",
  },
  patients: {
    search: "Search by name, city, or treatment",
    all: "All",
    alerts: "Alerts",
    noncompliant: "Non-compliant",
    onTrack: "On track",
    needsWatch: "Needs watch",
    filled: "Filled prescription",
    collected: "Collected",
    notCollected: "Not collected",
    takingMeds: "Taking meds this month",
    photos: "Photos this month",
    submitted: "Submitted",
    missing: "Missing",
    lastCheckIn: "Last check-in",
    yes: "Yes",
    no: "No",
    unknown: "Unknown",
    loadError: "Could not load patients. Is the local database running?",
    noneYet: "No patients are in treatment yet. Approve a case to add someone here.",
    noMatch: "No patients match this filter.",
  },
  messages: {
    search: "Search",
    all: "All",
    unread: "Unread",
    marked: "Marked",
    archived: "Archived",
    markRead: "Mark as read",
    markUnread: "Mark as unread",
    mark: "Mark",
    unmark: "Unmark",
    archive: "Archive",
    unarchive: "Unarchive",
    delete: "Delete chat",
    you: "You: ",
    write: "Write a message..",
    select: "Select a patient conversation.",
    loadError: "Could not load messages. Is the local database running?",
    empty: "No patient conversations yet.",
    noMatch: "No conversations match this search.",
    loading: "Loading messages…",
    back: "Back to conversations",
  },
  agenda: {
    week: "Week",
    month: "Month",
    previous: "Previous",
    next: "Next",
    invite: "Invite to video call",
    inviteTitle: "Invite a patient",
    patient: "Patient",
    selectPatient: "Select patient…",
    loadingWeek: "Loading week…",
    loadingMonth: "Loading month…",
    requested: "Patient request",
    scheduled: "Scheduled",
    completed: "Completed",
    cancelled: "Cancelled",
    loading: "Loading agenda…",
    dateTime: "Date and time",
    length: "Length",
    reason: "Reason",
    sendInvite: "Send invite",
    waitingConfirm: "Waiting for you to confirm",
    selectDay: "Select a day",
    loadError: "Could not load the agenda. Is the local database running?",
    emptyDay: "No video visits on this day. Invite a patient or confirm a request.",
    confirm: "Confirm",
    joinCall: "Join call",
    markComplete: "Mark complete",
    cancel: "Cancel",
    requestedByPatient: "Requested by patient",
    invitedByPhysician: "Invited by physician",
    weekdays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
  },
  settings: {
    appearance: "Appearance",
    appearanceHint: "Applies to the doctor portal on this device.",
    darkTheme: "Dark theme",
    darkHint: "Dim the charts and lists for evening work.",
    language: "Language",
    english: "English",
    turkish: "Türkçe",
    notifications: "Notifications",
    newCases: "New cases",
    visitRequests: "Visit requests",
    unreadMessages: "Unread messages",
    hours: "Working hours",
    hoursHint: "Used when proposing visit slots.",
    start: "Start",
    end: "End",
    defaultVisit: "Default visit",
    minutes: (n: number) => `${n} minutes`,
    days: {
      mon: "Mon",
      tue: "Tue",
      wed: "Wed",
      thu: "Thu",
      fri: "Fri",
      sat: "Sat",
      sun: "Sun",
    },
  },
  caseDetail: {
    back: "Back",
    caseReview: "Case Review",
    clinicalRecord: "Clinical Record",
    patientSummary: "Patient Summary",
    patient: "Patient",
    triageScore: "Triage score",
    reason: "Reason for consultation",
    affectedAreas: "Affected areas",
    location: "Location",
    reportedOnset: "Reported onset",
    currentMeds: "Current medications",
    medicalConditions: "Medical conditions",
    noneReported: "None reported",
    notProvided: "Not provided",
    photos: "Photos",
    previousTreatments: "Previous Hair Loss Treatments",
    treatmentsTried: "Treatments tried:",
    medicalAnswers: "Medical Answers",
    questions: (n: number) => `${n} questions`,
    ofPoints: (awarded: number, max: number) => `${awarded} of ${max} points`,
    noFlags: "No flags",
    itemsRequireReview: (n: number) => (n === 1 ? "Item Requires Review" : "Items Require Review") as string,
    highRisk: "high-risk",
    triageAssessment: "Triage Assessment",
    agaScore: "AGA Score",
    confidence: "Confidence",
    highRiskFindings: "High-Risk Findings (require escalation)",
    findingsReview: "Findings Requiring Physician Review",
    note: "Note:",
    noConcerns: "No concerns flagged. Pattern is consistent with androgenetic alopecia.",
    flagsIndicate: "System flags indicate additional physician review is required.",
    systemNotice: "System Notice:",
    systemNoticeBody:
      "This assessment is generated automatically from patient-reported information and images. It does not constitute a diagnosis or treatment recommendation. Final clinical decisions are made solely by the reviewing physician.",
    noFlagsRaised: "No flags raised during intake.",
    itemsFlagged: (n: number) => `${n} item${n > 1 ? "s" : ""} flagged for physician review.`,
    loading: "Loading case…",
    doctorActions: "Doctor Actions",
    approve: "Approve for Treatment",
    treatmentType: "Treatment Type *",
    selectTreatment: "Select treatment…",
    topicalFinasteride: "Topical Finasteride",
    topicalMinoxidil: "Topical Minoxidil",
    topicalCombo: "Topical Finasteride + Minoxidil",
    oralFinasteride: "Oral Finasteride",
    other: "Other",
    specifyTreatment: "Specify treatment *",
    enterTreatment: "Enter treatment…",
    followUp: "Follow-up *",
    selectFollowUp: "Select follow-up schedule…",
    month1: "1 month",
    month3: "3 months",
    month6: "6 months",
    noteOptional: "Note (optional)",
    optionalNote: "Optional note…",
    confirmApproval: "Confirm Approval",
    requestInfo: "Request More Info",
    reasonRequired: "Reason *",
    selectReason: "Select reason…",
    betterPhotos: "Better photos needed",
    clarifyMeds: "Clarify medications",
    clarifySymptoms: "Clarify symptoms",
    clarifyHistory: "Clarify medical history",
    additionalMessage: "Additional message (optional)",
    optionalMessage: "Optional message to patient…",
    sendRequest: "Send Request",
    decline: "Decline Case",
    declineReason: "Decline reason (internal notes) *",
    reasonPlaceholder: "Reason…",
    nextStep: "Recommended next step *",
    select: "Select…",
    inPerson: "In-person medical consultation",
    videoConsult: "Video consultation",
    phoneConsult: "Phone consultation",
    writtenOnly: "Written explanation only",
    confirmDecline: "Confirm Decline",
    override: "Override Triage",
    overrideTo: "Override to…",
    overrideGreen: "Green — low risk",
    overrideOrange: "Orange — needs review",
    overrideRed: "Red — escalate",
    caseMeta: (id: string, status: string, date: string) => `Case ${id} · ${status} ${date}`,
    clinicalTitle: "Patient Clinical Record",
    clinicalSubtitle: "Generated from immutable system records.",
    downloadRecord: "Download Full Patient Record",
    caseNumber: "Case Number",
    status: "Status",
    firstSubmitted: "First Submitted",
    lastActivity: "Last Activity",
    reportedIntake: "Patient-Reported Intake (at submission)",
    immutable: "Immutable Record",
    immutableBody:
      "This information was reported by the patient and is immutable after submission. Physician decision is based on this data.",
    hairLossHistory: "Hair Loss History",
    conditionsAndMeds: "Medical Conditions & Medications",
    previousTreatmentsHeading: "Previous Treatments",
    noPrevious: "No previous treatments reported",
    psychosocial: "Psychosocial Factors",
    triageBasis: "Triage Basis (System-Derived)",
    triageBasisSubtitle: "This assessment is automated scoring and flagging based on patient-reported data.",
    agaLikelihood: "AGA Likelihood Score",
    triageColor: "Triage Color",
    systemConfidence: "System Confidence",
    patternConsistency: "Pattern consistency",
    keyFactors: "Key Contributing Factors (Plain Language)",
    factorAga: "Multiple findings consistent with classic androgenetic alopecia pattern",
    factorFamily: "Strong family history present",
    factorPattern: "Typical AGA pattern (temples/crown)",
    consents: "Consents & Legal Acknowledgements",
    consentsSubtitle: "All patient consents with timestamps.",
    accepted: "Accepted",
    submittedPhotos: "Patient-Submitted Photos",
    submittedPhotosSubtitle: "Photos uploaded at time of submission. Physician decision is based on these images.",
    audit: "Audit Trail (Immutable)",
    auditSubtitle: "Chronological, append-only record of all actions related to this case. This record is immutable and cannot be deleted.",
    intakeSubmitted: "Intake submitted",
    caseCreated: "Case created",
    highLikelihood: "High likelihood",
    moderateLikelihood: "Moderate likelihood",
    lowLikelihood: "Low likelihood",
    routine: "Routine processing",
    needsReview: "Needs physician review",
    escalate: "Escalate for review",
    summaryVeryRecent: (onset: string) => `Very recent onset reported over the past ${onset}.`,
    summaryRecent: (onset: string) => `Recent onset reported over the past ${onset}.`,
    summaryProgressive: (onset: string) => `Progressive hair loss reported over the past ${onset}.`,
    summaryNoConditions: "No medical conditions disclosed.",
    summaryConditions: (list: string) => `Medical conditions reported: ${list}.`,
    summaryNoMeds: "No current medications reported.",
    summaryMeds: "Currently taking medications.",
    summaryImmediate: "Pattern requires immediate physician review.",
    summaryAga: "Pattern appears consistent with androgenetic alopecia.",
    summarySomeAga: "Pattern shows some characteristics of androgenetic alopecia.",
    summaryEvaluate: "Pattern requires physician evaluation.",
    summaryNoFlags: "No caution flags identified.",
    summaryOneFlag: "One caution flag identified for physician review.",
    summaryFlags: (n: number) => `${n} caution flags identified for physician review.`,
  },
  relative: {
    justNow: "just now",
    minute: "minute ago",
    minutes: "minutes ago",
    hour: "hour ago",
    hours: "hours ago",
    day: "day ago",
    days: "days ago",
  },
};

const tr: typeof en = {
  nav: {
    now: "Son hareketler",
    cases: "Vakalar",
    patients: "Hastalar",
    agenda: "Ajanda",
    messages: "Mesajlar",
    settings: "Ayarlar",
  },
  header: {
    languageEn: "EN",
    languageTr: "TR",
    account: "Hesap",
    settings: "Ayarlar",
    logout: "Çıkış",
    signedInAs: "Giriş yapan",
  },
  pages: {
    now: "Son hareketler",
    cases: "Vaka özeti",
    patients: "Tedavideki hastalar",
    agenda: "Ajanda",
    messages: "Mesajlar",
    settings: "Ayarlar",
    patientProfile: "Hasta profili",
    patientNotFound: "Hasta bulunamadı",
  },
  now: {
    loading: "Kuyruk yükleniyor…",
    empty: "Bekleyen bir şey yok. Yeni vakalar, görüşme istekleri, bugünkü aramalar ve okunmamış mesajlar burada görünür.",
    newCase: "Yeni vaka",
    visitRequest: "Görüşme isteği",
    callToday: "Bugünkü arama",
    unreadMessage: "Okunmamış mesaj",
  },
  cases: {
    search: "Vaka kodu ile ara",
    pending: "İnceleme bekliyor",
    approved: "Onaylandı",
    declined: "Reddedildi",
    all: "Tüm vakalar",
    flagged: "Yalnızca işaretliler",
    red: "Yalnızca kırmızı",
    orange: "Yalnızca turuncu",
    green: "Yalnızca yeşil",
    infoRequested: "Bilgi istendi",
    refresh: "Yenile",
    empty: "Bu görünümde vaka yok.",
    emptyNone: "Henüz gönderilmiş başvuru yok. Tamamlanan hasta başvuruları burada görünür.",
    emptyTab: "Bu sekmede gösterilecek vaka yok.",
  },
  patients: {
    search: "Ad, şehir veya tedavi ile ara",
    all: "Tümü",
    alerts: "Uyarılar",
    noncompliant: "Uyum yok",
    onTrack: "Yolunda",
    needsWatch: "İzlenmeli",
    filled: "Reçete",
    collected: "Alındı",
    notCollected: "Alınmadı",
    takingMeds: "Bu ay ilaç kullanımı",
    photos: "Bu ay fotoğraf",
    submitted: "Gönderildi",
    missing: "Eksik",
    lastCheckIn: "Son check-in",
    yes: "Evet",
    no: "Hayır",
    unknown: "Bilinmiyor",
    loadError: "Hastalar yüklenemedi. Yerel veritabanı çalışıyor mu?",
    noneYet: "Henüz tedavide hasta yok. Bir vakayı onaylayınca burada görünür.",
    noMatch: "Bu filtreye uyan hasta yok.",
  },
  messages: {
    search: "Ara",
    all: "Tümü",
    unread: "Okunmamış",
    marked: "İşaretli",
    archived: "Arşiv",
    markRead: "Okundu işaretle",
    markUnread: "Okunmadı işaretle",
    mark: "İşaretle",
    unmark: "İşareti kaldır",
    archive: "Arşivle",
    unarchive: "Arşivden çıkar",
    delete: "Sohbeti sil",
    you: "Siz: ",
    write: "Mesaj yazın..",
    select: "Bir hasta sohbeti seçin.",
    loadError: "Mesajlar yüklenemedi. Yerel veritabanı çalışıyor mu?",
    empty: "Henüz hasta sohbeti yok.",
    noMatch: "Bu aramaya uyan sohbet yok.",
    loading: "Mesajlar yükleniyor…",
    back: "Sohbetlere dön",
  },
  agenda: {
    week: "Hafta",
    month: "Ay",
    previous: "Önceki",
    next: "Sonraki",
    invite: "Görüntülü aramaya davet et",
    inviteTitle: "Hastayı davet et",
    patient: "Hasta",
    selectPatient: "Hasta seçin…",
    loadingWeek: "Hafta yükleniyor…",
    loadingMonth: "Ay yükleniyor…",
    requested: "Hasta isteği",
    scheduled: "Planlandı",
    completed: "Tamamlandı",
    cancelled: "İptal",
    loading: "Ajanda yükleniyor…",
    dateTime: "Tarih ve saat",
    length: "Süre",
    reason: "Neden",
    sendInvite: "Davet gönder",
    waitingConfirm: "Onayınızı bekliyor",
    selectDay: "Bir gün seçin",
    loadError: "Ajanda yüklenemedi. Yerel veritabanı çalışıyor mu?",
    emptyDay: "Bu günde görüntülü görüşme yok. Hasta davet edin veya bir isteği onaylayın.",
    confirm: "Onayla",
    joinCall: "Aramaya katıl",
    markComplete: "Tamamlandı işaretle",
    cancel: "İptal",
    requestedByPatient: "Hasta tarafından istendi",
    invitedByPhysician: "Hekim tarafından davet edildi",
    weekdays: ["Pzt", "Sal", "Çar", "Per", "Cum", "Cmt", "Paz"],
  },
  settings: {
    appearance: "Görünüm",
    appearanceHint: "Bu cihazdaki hekim paneline uygulanır.",
    darkTheme: "Koyu tema",
    darkHint: "Akşam kullanımı için listeleri karartır.",
    language: "Dil",
    english: "English",
    turkish: "Türkçe",
    notifications: "Bildirimler",
    newCases: "Yeni vakalar",
    visitRequests: "Görüşme istekleri",
    unreadMessages: "Okunmamış mesajlar",
    hours: "Çalışma saatleri",
    hoursHint: "Görüşme slotları önerilirken kullanılır.",
    start: "Başlangıç",
    end: "Bitiş",
    defaultVisit: "Varsayılan görüşme",
    minutes: (n: number) => `${n} dakika`,
    days: {
      mon: "Pzt",
      tue: "Sal",
      wed: "Çar",
      thu: "Per",
      fri: "Cum",
      sat: "Cmt",
      sun: "Paz",
    },
  },
  caseDetail: {
    back: "Geri",
    caseReview: "Vaka incelemesi",
    clinicalRecord: "Klinik kayıt",
    patientSummary: "Hasta özeti",
    patient: "Hasta",
    triageScore: "Triyaj skoru",
    reason: "Konsültasyon nedeni",
    affectedAreas: "Etkilenen bölgeler",
    location: "Konum",
    reportedOnset: "Bildirilen başlangıç",
    currentMeds: "Mevcut ilaçlar",
    medicalConditions: "Tıbbi durumlar",
    noneReported: "Bildirilmedi",
    notProvided: "Belirtilmedi",
    photos: "Fotoğraflar",
    previousTreatments: "Önceki saç kaybı tedavileri",
    treatmentsTried: "Denenen tedaviler:",
    medicalAnswers: "Tıbbi yanıtlar",
    questions: (n: number) => `${n} soru`,
    ofPoints: (awarded: number, max: number) => `${awarded} / ${max} puan`,
    noFlags: "İşaret yok",
    itemsRequireReview: (n: number) => (n === 1 ? "İnceleme gereken madde" : "İnceleme gereken maddeler") as string,
    highRisk: "yüksek risk",
    triageAssessment: "Triyaj değerlendirmesi",
    agaScore: "AGA skoru",
    confidence: "Güven",
    highRiskFindings: "Yüksek riskli bulgular (yükseltme gerekir)",
    findingsReview: "Hekim incelemesi gereken bulgular",
    note: "Not:",
    noConcerns: "Endişe işaretlenmedi. Patern androgenetik alopesi ile uyumlu.",
    flagsIndicate: "Sistem işaretleri ek hekim incelemesi gerektiğini gösteriyor.",
    systemNotice: "Sistem bildirimi:",
    systemNoticeBody:
      "Bu değerlendirme, hastanın bildirdiği bilgiler ve görüntülerden otomatik üretilir. Tanı veya tedavi önerisi değildir. Nihai klinik karar yalnızca inceleyen hekime aittir.",
    noFlagsRaised: "Başvuruda işaret yükselmedi.",
    itemsFlagged: (n: number) => `${n} madde hekim incelemesi için işaretlendi.`,
    loading: "Vaka yükleniyor…",
    doctorActions: "Hekim işlemleri",
    approve: "Tedavi için onayla",
    treatmentType: "Tedavi türü *",
    selectTreatment: "Tedavi seçin…",
    topicalFinasteride: "Topikal Finasterid",
    topicalMinoxidil: "Topikal Minoksidil",
    topicalCombo: "Topikal Finasterid + Minoksidil",
    oralFinasteride: "Ağızdan Finasterid",
    other: "Diğer",
    specifyTreatment: "Tedaviyi belirtin *",
    enterTreatment: "Tedaviyi yazın…",
    followUp: "Takip *",
    selectFollowUp: "Takip takvimini seçin…",
    month1: "1 ay",
    month3: "3 ay",
    month6: "6 ay",
    noteOptional: "Not (isteğe bağlı)",
    optionalNote: "İsteğe bağlı not…",
    confirmApproval: "Onayı onayla",
    requestInfo: "Ek bilgi iste",
    reasonRequired: "Neden *",
    selectReason: "Neden seçin…",
    betterPhotos: "Daha iyi fotoğraf gerekli",
    clarifyMeds: "İlaçları netleştir",
    clarifySymptoms: "Belirtileri netleştir",
    clarifyHistory: "Tıbbi öyküyü netleştir",
    additionalMessage: "Ek mesaj (isteğe bağlı)",
    optionalMessage: "Hastaya isteğe bağlı mesaj…",
    sendRequest: "İstek gönder",
    decline: "Vakayı reddet",
    declineReason: "Red nedeni (dahili notlar) *",
    reasonPlaceholder: "Neden…",
    nextStep: "Önerilen sonraki adım *",
    select: "Seçin…",
    inPerson: "Yüz yüze tıbbi konsültasyon",
    videoConsult: "Görüntülü konsültasyon",
    phoneConsult: "Telefon konsültasyonu",
    writtenOnly: "Yalnızca yazılı açıklama",
    confirmDecline: "Reddi onayla",
    override: "Triyajı geçersiz kıl",
    overrideTo: "Şuna değiştir…",
    overrideGreen: "Yeşil — düşük risk",
    overrideOrange: "Turuncu — inceleme gerekir",
    overrideRed: "Kırmızı — yükselt",
    caseMeta: (id: string, status: string, date: string) => `Vaka ${id} · ${status} ${date}`,
    clinicalTitle: "Hasta klinik kaydı",
    clinicalSubtitle: "Değiştirilemez sistem kayıtlarından oluşturulur.",
    downloadRecord: "Tam hasta kaydını indir",
    caseNumber: "Vaka numarası",
    status: "Durum",
    firstSubmitted: "İlk gönderim",
    lastActivity: "Son hareket",
    reportedIntake: "Hastanın bildirdiği form (gönderim anında)",
    immutable: "Değiştirilemez kayıt",
    immutableBody:
      "Bu bilgiler hasta tarafından bildirildi ve gönderimden sonra değiştirilemez. Hekim kararı bu verilere dayanır.",
    hairLossHistory: "Saç kaybı öyküsü",
    conditionsAndMeds: "Tıbbi durumlar ve ilaçlar",
    previousTreatmentsHeading: "Önceki tedaviler",
    noPrevious: "Önceki tedavi bildirilmedi",
    psychosocial: "Psikososyal faktörler",
    triageBasis: "Triyaj dayanağı (sistem türevi)",
    triageBasisSubtitle: "Bu değerlendirme, hastanın bildirdiği verilere dayalı otomatik skor ve işaretlemedir.",
    agaLikelihood: "AGA olasılık skoru",
    triageColor: "Triyaj rengi",
    systemConfidence: "Sistem güveni",
    patternConsistency: "Patern tutarlılığı",
    keyFactors: "Ana katkı faktörleri (sade dil)",
    factorAga: "Klasik androgenetik alopesi paterniyle uyumlu birden fazla bulgu",
    factorFamily: "Güçlü aile öyküsü var",
    factorPattern: "Tipik AGA paterni (şakaklar/tepe)",
    consents: "Onamlar ve yasal onaylar",
    consentsSubtitle: "Zaman damgalı tüm hasta onamları.",
    accepted: "Kabul edildi",
    submittedPhotos: "Hastanın gönderdiği fotoğraflar",
    submittedPhotosSubtitle: "Gönderim anında yüklenen fotoğraflar. Hekim kararı bu görüntülere dayanır.",
    audit: "Denetim izi (değiştirilemez)",
    auditSubtitle: "Bu vakayla ilgili tüm işlemlerin kronolojik, yalnızca eklenen kaydı. Silinemez.",
    intakeSubmitted: "Form gönderildi",
    caseCreated: "Vaka oluşturuldu",
    highLikelihood: "Yüksek olasılık",
    moderateLikelihood: "Orta olasılık",
    lowLikelihood: "Düşük olasılık",
    routine: "Rutin işlem",
    needsReview: "Hekim incelemesi gerekir",
    escalate: "İnceleme için yükselt",
    summaryVeryRecent: (onset: string) => `Çok yeni başlangıç bildirildi: ${onset}.`,
    summaryRecent: (onset: string) => `Yakın dönem başlangıç bildirildi: ${onset}.`,
    summaryProgressive: (onset: string) => `İlerleyici saç kaybı bildirildi: ${onset}.`,
    summaryNoConditions: "Tıbbi durum açıklanmadı.",
    summaryConditions: (list: string) => `Bildirilen tıbbi durumlar: ${list}.`,
    summaryNoMeds: "Mevcut ilaç bildirilmedi.",
    summaryMeds: "Şu an ilaç kullanıyor.",
    summaryImmediate: "Patern acil hekim incelemesi gerektiriyor.",
    summaryAga: "Patern androgenetik alopesi ile uyumlu görünüyor.",
    summarySomeAga: "Patern androgenetik alopesinin bazı özelliklerini gösteriyor.",
    summaryEvaluate: "Patern hekim değerlendirmesi gerektiriyor.",
    summaryNoFlags: "Uyarı işareti yok.",
    summaryOneFlag: "Hekim incelemesi için bir uyarı işareti belirlendi.",
    summaryFlags: (n: number) => `Hekim incelemesi için ${n} uyarı işareti belirlendi.`,
  },
  relative: {
    justNow: "az önce",
    minute: "dakika önce",
    minutes: "dakika önce",
    hour: "saat önce",
    hours: "saat önce",
    day: "gün önce",
    days: "gün önce",
  },
};

export const doctorCopy = { en, tr };
export type DoctorCopy = typeof en;

export function formatDoctorRelativeTime(copy: DoctorCopy, timestamp: number | undefined): string {
  if (!timestamp || Number.isNaN(timestamp)) return copy.relative.justNow;
  const diffMs = Date.now() - timestamp;
  const diffMinutes = Math.floor(diffMs / (1000 * 60));
  const diffHours = Math.floor(diffMs / (1000 * 60 * 60));
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));
  if (diffMinutes < 1) return copy.relative.justNow;
  if (diffMinutes < 60) return `${diffMinutes} ${diffMinutes === 1 ? copy.relative.minute : copy.relative.minutes}`;
  if (diffHours < 24) return `${diffHours} ${diffHours === 1 ? copy.relative.hour : copy.relative.hours}`;
  return `${diffDays} ${diffDays === 1 ? copy.relative.day : copy.relative.days}`;
}
