import type { Metadata } from "next";
import { LegalPage, LegalSection, legalLinkClassName, legalListClassName } from "@/components/LegalPage";

export const metadata: Metadata = {
  title: "Terms and Conditions | Hiros",
  description: "Terms and Conditions governing access to the Hiros website and demo.",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms and Conditions" lastUpdated="21 August 2026">
      <LegalSection title="Scope and Acceptance">
        <p>
          These Terms and Conditions (“Terms”) govern access to and use of the website located at [insert domain] (the
          “Website”) and any demonstration version of the Hiros software platform made available through it or shown in
          person, by video, or remotely (the “Demo”). By accessing the Website or participating in a Demo, you (“User,”
          “you”) agree to be bound by these Terms.
        </p>
        <p>
          Hiros is currently being established as a legal entity in the Republic of Türkiye (“Hiros,” “we,” “us”). Until
          incorporation is finalized, these Terms are issued on behalf of the founding team operating under the Hiros
          name.
        </p>
      </LegalSection>

      <LegalSection title="Current Stage of the Platform — Demo Only">
        <p>
          The Hiros application shown in any Demo is a work-in-progress technology demonstration. It is{" "}
          <strong>not</strong> a certified, licensed, or legally operative medical software product. Specifically:
        </p>
        <ul className={legalListClassName}>
          <li>The Demo does not provide medical consultations, diagnoses, prescriptions, or treatment of any kind.</li>
          <li>
            The Demo must not be used to enter, store, or process <strong>real, identifiable patient data</strong>. Any
            data entered during a Demo — including intake answers, photographs, or health information — must be
            fictitious, anonymized, or synthetic test data only.
          </li>
          <li>
            No output, risk assessment, triage suggestion, or workflow result generated by the Demo should be relied upon
            for any actual clinical or patient-care decision.
          </li>
          <li>
            Hiros makes no representation that the Demo reflects the final, production version of the platform in
            features, accuracy, security posture, or regulatory compliance.
          </li>
        </ul>
        <p>
          By participating in a Demo, you confirm that you understand its purpose is solely to illustrate intended
          functionality, and you agree not to input any real patient’s personal or health data into it.
        </p>
      </LegalSection>

      <LegalSection title="Confidentiality and Intellectual Property">
        <p>
          Access to the Demo may involve exposure to unreleased features, workflows, designs, and business methods that
          are confidential and proprietary to Hiros. By participating in a Demo, you agree to:
        </p>
        <ul className={legalListClassName}>
          <li>
            Keep confidential any non-public information about the Demo, including its functionality, design, underlying
            logic, and any materials shared during the demonstration, except where you have Hiros’ prior written consent
            to disclose it or disclosure is required by law.
          </li>
          <li>
            Not copy, reverse-engineer, decompile, or attempt to extract the underlying source code, algorithms, or
            business logic of the Demo.
          </li>
          <li>Not use anything observed during the Demo to develop a competing product or service.</li>
        </ul>
        <p>
          All content on the Website and within the Demo — including text, graphics, logos, product design, and
          underlying software — is the intellectual property of Hiros (or its licensors) and may not be reproduced,
          distributed, or used without prior written permission.
        </p>
      </LegalSection>

      <LegalSection title="No Medical Advice; No Warranty">
        <p>
          Nothing on the Website or in the Demo constitutes medical advice. The Website is provided for informational
          purposes only. All medical decisions remain the sole responsibility of licensed physicians using their own
          professional judgment.
        </p>
        <p>
          The Website and the Demo are provided “as is” and “as available,” without warranties of any kind, express or
          implied, including but not limited to fitness for a particular purpose, accuracy, or uninterrupted availability
          — consistent with their current stage of development.
        </p>
      </LegalSection>

      <LegalSection title="Limitation of Liability">
        <p>
          To the maximum extent permitted under Turkish law, Hiros shall not be liable for any indirect, incidental, or
          consequential damages arising from access to the Website or participation in a Demo.
        </p>
        <p>
          Consistent with Article 115 of the Turkish Code of Obligations (Law No. 6098), nothing in these Terms limits or
          excludes liability for damages caused by gross negligence or willful misconduct, which cannot be waived under
          Turkish law.
        </p>
      </LegalSection>

      <LegalSection title="Personal Data">
        <p>
          Any personal data collected through the Website (for example, via a contact form) or in connection with
          arranging a Demo is processed in accordance with our{" "}
          <a href="/privacy" className={legalLinkClassName}>
            Privacy Policy
          </a>{" "}
          and Türkiye’s Personal Data Protection Law No. 6698 (“KVKK”). Where a Demo session involves any incidental
          processing of a User’s own personal data (such as your name and professional affiliation, provided for
          scheduling purposes), this is limited strictly to what is necessary to arrange and conduct the demonstration.
        </p>
        <p>
          Sensitive personal data, including health data, may under KVKK only be processed with explicit consent or
          another lawful basis specifically permitted by law. As stated in Current Stage of the Platform — Demo Only, real
          patient health data must never be entered into the Demo, and no such data is knowingly collected or processed by
          Hiros at this stage.
        </p>
      </LegalSection>

      <LegalSection title="No Commercial Transaction">
        <p>
          No goods, services, subscriptions, or licenses are currently sold, ordered, or contracted through the Website.
          Accordingly, the order-formation and distance-contract provisions of Türkiye’s E-Commerce Law No. 6563 do not
          currently apply. Should Hiros begin offering paid services through the Website in the future, these Terms will
          be updated accordingly, and the applicable e-commerce disclosures will be added at that time.
        </p>
      </LegalSection>

      <LegalSection title="Changes to the Demo or These Terms">
        <p>
          Hiros may modify, suspend, or discontinue the Demo, or any feature within it, at any time without notice, given
          its current development stage. We may update these Terms as the platform evolves; continued use of the Website
          or participation in future Demos constitutes acceptance of the then-current Terms.
        </p>
      </LegalSection>

      <LegalSection title="Governing Law and Jurisdiction">
        <p>
          These Terms are governed by the laws of the Republic of Türkiye. Any dispute arising from these Terms shall be
          subject to the exclusive jurisdiction of the courts of [insert city — likely Istanbul, once your operating base
          is confirmed].
        </p>
      </LegalSection>

      <LegalSection title="Contact">
        <p>
          Questions about these Terms can be sent to{" "}
          <a href="mailto:info@hiros.com.tr" className={legalLinkClassName}>
            info@hiros.com.tr
          </a>
          .
        </p>
      </LegalSection>
    </LegalPage>
  );
}
