import type { Metadata } from "next";
import { LegalNotice, LegalPage, LegalSection, legalLinkClassName, legalListClassName } from "@/components/LegalPage";

export const metadata: Metadata = {
  title: "Telehealth / Remote Service Consent | Hiros",
  description: "Forward-looking consent for remote follow-up care provided through Hiros.",
};

export default function TelehealthConsentPage() {
  return (
    <LegalPage title="Telehealth / Remote Service Consent" lastUpdated="21 August 2026">
      <LegalNotice>
        Forward-looking — for use once a partner clinic is providing remote/digital follow-up care to patients through
        Hiros. Not in effect during the current demo stage.
      </LegalNotice>

      <LegalSection title="Important Scope Note">
        <LegalNotice>
          This consent covers the technology-mediated aspects of using Hiros to receive remote, asynchronous follow-up
          care from your clinic — communicating through the platform, submitting photos and questionnaire responses, and
          receiving reminders. It does not replace, and is separate from, the informed consent your physician must obtain
          directly from you for any specific diagnosis or treatment decision, as required under Article 70 of Law No. 1219
          and Articles 24–31 of the Patient Rights Regulation. That clinical consent remains your treating physician’s
          direct responsibility and must cover your diagnosis, the proposed intervention, alternatives, risks, expected
          benefits, and consequences of declining treatment — a general platform checkbox cannot substitute for it.
        </LegalNotice>
      </LegalSection>

      <LegalSection title="What You’re Consenting To">
        <p>By using Hiros to receive follow-up care from your clinic, you acknowledge and agree that:</p>
        <ul className={legalListClassName}>
          <li>
            Your clinic is providing remote health services to you through Hiros in accordance with Türkiye’s Regulation
            on the Provision of Remote Health Services (Uzaktan Sağlık Hizmetlerinin Sunumu Hakkında Yönetmelik). Your
            clinic confirms it holds any Ministry of Health authorization required to provide remote health services, and
            that this authorization covers the services provided to you through this platform.
          </li>
          <li>
            Communication through Hiros (messages, photos, questionnaire responses) will be reviewed by your treating
            physician or their clinical team, not automatically acted upon by software alone.
          </li>
          <li>
            Any risk-assessment or triage indicators generated by the platform are decision-support only and do not
            constitute a diagnosis; only your physician can diagnose or prescribe treatment.
          </li>
          <li>
            You understand the limitations of remote monitoring compared to an in-person examination, and that your
            physician may require an in-person visit if remote information is insufficient.
          </li>
          <li>
            Your health data submitted through the platform will be processed as described in the{" "}
            <a href="/health-privacy" className={legalLinkClassName}>
              Consumer/Patient Health Data Privacy Policy
            </a>
            .
          </li>
          <li>
            You may withdraw this consent at any time by notifying your clinic, without affecting your right to receive
            care through other means.
          </li>
        </ul>
      </LegalSection>

      <LegalSection title="Physician/Clinic Responsibility">
        <p>
          Nothing in this consent shifts responsibility for clinical decision-making, diagnosis, or treatment away from
          the treating physician and clinic, who remain bound by their obligations under Law No. 1219, the Patient Rights
          Regulation, and Ministry of Health remote health service requirements.
        </p>
      </LegalSection>

      <LegalSection title="Contact">
        <p>
          Questions about this consent can be directed to your treating clinic, or to{" "}
          <a href="mailto:info@hiros.com.tr" className={legalLinkClassName}>
            info@hiros.com.tr
          </a>
          .
        </p>
      </LegalSection>
    </LegalPage>
  );
}
